name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Build de l’image Docker
        run: docker build -t flask-k8-example .

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Scan des dépendances avec Trivy
        id: trivy-deps
        run: |
          trivy fs --severity CRITICAL --ignore-unfixed --exit-code 1 --format table --output trivy-deps-report.txt .
        continue-on-error: true

      - name: Scan de l’image Docker avec Trivy
        id: trivy-image
        run: |
          trivy image --severity CRITICAL --ignore-unfixed --exit-code 1 --format table --output trivy-image-report.txt flask-k8-example
        continue-on-error: true

      - name: Upload des rapports Trivy
        uses: actions/upload-artifact@v4
        with:
          name: trivy-reports
          path: |
            trivy-deps-report.txt
            trivy-image-report.txt

      - name: Vérification des résultats Trivy
        run: |
          if [ "${{ steps.trivy-deps.outcome }}" == "failure" ] || [ "${{ steps.trivy-image.outcome }}" == "failure" ]; then
            echo "Trivy a détecté des vulnérabilités CRITIQUES !"
            exit 1
          else
            echo "Aucun problème critique détecté par Trivy."
          fi

      - name: Lint Dockerfile (Hadolint)
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Installation de yamllint
        run: pip install yamllint

      - name: Lint les fichiers YAML
        run: yamllint deployment.yaml service.yaml
        
      - name: Install Conftest
        run: |
         wget https://github.com/open-policy-agent/conftest/releases/download/v0.52.0/conftest_0.52.0_Linux_x86_64.tar.gz
         tar xzf conftest_0.52.0_Linux_x86_64.tar.gz
         mv conftest /usr/local/bin/

