name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Build de l’image Docker
        run: docker build -t flask-k8-example .
        
      - name: Lint Dockerfile (Hadolint)
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          config: .hadolint.yaml
          
      - name: Installation de yamllint
        run: pip install yamllint

      - name: Lint les fichiers YAML
        run: yamllint deployment.yaml service.yaml

